"""Generate the bundled CLI command reference from the live Typer help model."""

from __future__ import annotations

import argparse
from pathlib import Path

from typer import _click as click
from typer.core import TyperGroup, TyperOption
from typer.main import get_command

from arcavex.clients.cli import app

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "skills/arcavex-design-studio/references/commands.md"


def render_reference() -> str:
    lines = [
        "# CLI command reference",
        "",
        "Generated by `scripts/generate_skill_reference.py` "
        "from the running CLI's help model. Use `arcavex COMMAND --help` for arguments, "
        "defaults, and examples.",
        "",
        "| Command | Purpose | Options |",
        "|---|---|---|",
    ]

    def visit(command: click.Command, prefix: str) -> None:
        ctx = click.Context(command, info_name=prefix)
        if isinstance(command, TyperGroup):
            for name in sorted(command.commands):
                visit(command.commands[name], f"{prefix} {name}")
            return
        options = ["/".join(p.opts) for p in command.params if isinstance(p, TyperOption)]
        purpose = command.get_short_help_str(limit=240).replace("|", "\\|").replace("\n", " ")
        flags = ", ".join(f"`{flag}`" for flag in options)
        lines.append(f"| `{prefix}` | {purpose} | {flags} |")
        ctx.close()

    visit(get_command(app), "arcavex")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail on a stale bundled reference.")
    args = parser.parse_args()
    content = render_reference()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != content:
            print("Bundled command reference is stale; run scripts/generate_skill_reference.py")
            return 1
    else:
        OUTPUT.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
