// Generated by scripts/generate_desktop_contracts.mjs. Do not edit.

import assert from "node:assert/strict";
import test from "node:test";

import {
  desktopContractFixtures,
  desktopContractGuards,
  desktopContractNames,
} from "./generated.ts";

test("Pydantic-serialized fixtures satisfy every generated desktop guard", () => {
  for (const name of desktopContractNames) {
    assert.equal(desktopContractGuards[name](desktopContractFixtures[name]), true, name);
  }
});

test("generated desktop guards reject malformed and version-wrong reports", () => {
  for (const name of desktopContractNames) {
    const fixture = desktopContractFixtures[name];
    const malformed = { ...fixture };
    delete malformed.ok;

    assert.equal(desktopContractGuards[name](malformed), false, `${name} malformed`);
    assert.equal(
      desktopContractGuards[name]({ ...fixture, response_version: 2 }),
      false,
      `${name} version`,
    );
  }
});
