// Generated by scripts/generate_desktop_contracts.mjs. Do not edit.

export type AutomationPolicy = { readonly extensions?: "unrestricted" | "disabled"; readonly mode?: "unrestricted" | "review" | "read_only"; readonly version?: 1; };

export type Diagnostic = { readonly code: string; readonly hint?: string | null; readonly message: string; readonly severity?: "error" | "warning" | "info"; readonly source?: SourceLocation | null; };

export type DoctorCheck = { readonly detail: string; readonly hint?: string | null; readonly name: string; readonly status: "ok" | "warn" | "fail"; };

export type DoctorReport = { readonly checks: ReadonlyArray<DoctorCheck>; readonly engine_version: string; readonly ok: boolean; readonly response_version?: number; };

export type EngineIdentity = { readonly artifact_path?: string | null; readonly artifact_sha256?: string | null; readonly build_commit?: string | null; readonly engine_version: string; };

export type EnginePaths = { readonly assets: string; readonly cache: string; readonly extensions: string; readonly fonts: string; readonly home: string; readonly styles: string; readonly templates: string; };

export type HitCandidate = { readonly authored_id: string; readonly bounds_pt: readonly [number, number, number, number]; readonly display_name: string; readonly editable: boolean; readonly id: string; readonly instance_id: string; readonly kind: "group" | "text" | "image" | "shape" | "path"; readonly locked: boolean; readonly paint_bounds_pt: readonly [number, number, number, number]; readonly parent_id?: string | null; };

export type LayerEffect = { readonly category?: "geometry" | "color" | "raster" | "composite" | null; readonly index: number; readonly name: string; readonly params?: Readonly<Record<string, never>>; };

export type LayerMask = { readonly component: string; readonly params?: Readonly<Record<string, never>>; };

export type LayerNodeReport = { readonly absolute_transform?: readonly [number, number, number, number, number, number] | null; readonly authored_id: string; readonly authored_index: number; readonly bounds_pt?: readonly [number, number, number, number] | null; readonly bounds_px?: readonly [number, number, number, number] | null; readonly children?: ReadonlyArray<LayerNodeReport>; readonly collection?: string | null; readonly color?: string | null; readonly condition?: string | null; readonly display_name: string; readonly editable?: boolean; readonly effects?: ReadonlyArray<LayerEffect>; readonly hit_testable?: boolean; readonly id: string; readonly instance_id?: string | null; readonly key?: string | null; readonly kind: string; readonly locked?: boolean; readonly loop_var?: string | null; readonly mask?: LayerMask | null; readonly origin?: "static" | "repeat" | "if"; readonly overflow?: OverflowReport | null; readonly paint_bounds_pt?: readonly [number, number, number, number] | null; readonly paint_bounds_px?: readonly [number, number, number, number] | null; readonly paint_index?: number | null; readonly parent_id?: string | null; readonly rotate_deg?: number; readonly source?: LayerSource | null; readonly virtual?: boolean; readonly visible?: boolean; readonly z?: number; };

export type LayerSource = { readonly file?: string | null; readonly keypath?: string | null; readonly line?: number | null; };

export type LayerUIMetadata = { readonly color?: string | null; readonly display_name?: string | null; readonly locked?: boolean; };

export type OverflowReport = { readonly box_h_pt: number; readonly box_w_pt: number; readonly kind: string; readonly measured_h_pt: number; readonly measured_w_pt: number; };

export type PreviewResult = { readonly changed_file?: string | null; readonly compile_ms?: number | null; readonly content_sha256?: string | null; readonly diagnostics?: ReadonlyArray<Diagnostic>; readonly inferred?: { readonly [key: string]: unknown; }; readonly ok: boolean; readonly output_path?: string | null; readonly render_ms?: number | null; readonly response_version?: number; };

export type ProjectProposal = { readonly actor: ProposalActor; readonly base_project_revision: string; readonly command_id: string; readonly command_payload: Readonly<Record<string, never>>; readonly created_at: string; readonly project_path: string; readonly rejection_reason?: string | null; readonly state?: "pending" | "authorized" | "rejected"; readonly version?: 1; };

export type ProjectSourceFile = { readonly path: string; readonly project_owned: boolean; readonly resolved_path: string; readonly role: "project" | "ui" | "template" | "data" | "override" | "asset"; readonly sha256?: string | null; };

export type ProjectTarget = { readonly format: string; readonly locale?: string | null; };

export type ProjectUIMetadata = { readonly layers?: { readonly [key: string]: unknown; }; readonly version?: 1; readonly workspace?: ProjectWorkspaceState; };

export type ProjectWorkspaceState = { readonly active_format?: string | null; readonly active_locale?: string | null; readonly layer_tree_mode?: "definition" | "rendered"; readonly selected_layer_ids?: ReadonlyArray<string>; };

export type ProposalActor = { readonly display_name?: string | null; readonly id: string; };

export type RevisionManifestEntry = { readonly bytes: number; readonly path: string; readonly sha256: string; };

export type SourceLocation = { readonly column?: number | null; readonly file?: string | null; readonly keypath?: string | null; readonly line?: number | null; };

export type CheckResult = { readonly diagnostics?: ReadonlyArray<Diagnostic>; readonly ok: boolean; readonly response_version?: number; };

export type EngineHandshakeReport = { readonly accepted_ir_versions: ReadonlyArray<string>; readonly capabilities: ReadonlyArray<string>; readonly diagnostics?: ReadonlyArray<Diagnostic>; readonly doctor: DoctorReport; readonly extension_sdk_version: string; readonly identity: EngineIdentity; readonly mcp_contract_version: string; readonly ok: boolean; readonly paths: EnginePaths; readonly produced_ir_version: string; readonly response_version?: number; };

export type HitTestReport = { readonly candidates?: ReadonlyArray<HitCandidate>; readonly diagnostics?: ReadonlyArray<Diagnostic>; readonly format?: string | null; readonly locale?: string | null; readonly ok: boolean; readonly point_pt?: readonly [number, number]; readonly point_px?: readonly [number, number] | null; readonly response_version?: number; };

export type LayerTreeReport = { readonly canvas_pt?: readonly [number, number]; readonly canvas_px?: readonly [number, number]; readonly diagnostics?: ReadonlyArray<Diagnostic>; readonly dpi?: number; readonly format?: string | null; readonly locale?: string | null; readonly mode?: "authored" | "rendered"; readonly ok: boolean; readonly response_version?: number; readonly root?: LayerNodeReport | null; };

export type PreviewProjectReport = { readonly diagnostics?: ReadonlyArray<Diagnostic>; readonly ok: boolean; readonly previews?: ReadonlyArray<PreviewResult>; readonly response_version?: number; };

export type ProjectPolicyReport = { readonly canonical_path?: string | null; readonly diagnostics?: ReadonlyArray<Diagnostic>; readonly ok: boolean; readonly policy?: AutomationPolicy; readonly project_revision?: string | null; readonly render_revision?: string | null; readonly response_version?: number; };

export type ProjectSnapshotReport = { readonly canonical_path?: string | null; readonly capabilities?: ReadonlyArray<string>; readonly data?: string | null; readonly default_target?: ProjectTarget | null; readonly diagnostics?: ReadonlyArray<Diagnostic>; readonly dpi?: number | null; readonly formats?: ReadonlyArray<string>; readonly locales?: ReadonlyArray<string>; readonly name?: string | null; readonly ok: boolean; readonly project_manifest?: ReadonlyArray<RevisionManifestEntry>; readonly project_revision?: string | null; readonly render_manifest?: ReadonlyArray<RevisionManifestEntry>; readonly render_revision?: string | null; readonly response_version?: number; readonly source_files?: ReadonlyArray<ProjectSourceFile>; readonly status?: string | null; readonly style?: string | null; readonly tags?: ReadonlyArray<string>; readonly targets?: ReadonlyArray<ProjectTarget>; readonly template?: string | null; };

export type ProjectUIMetadataReport = { readonly canonical_path?: string | null; readonly diagnostics?: ReadonlyArray<Diagnostic>; readonly metadata?: ProjectUIMetadata; readonly ok: boolean; readonly project_revision?: string | null; readonly render_revision?: string | null; readonly response_version?: number; };

export type ProposalActionReport = { readonly canonical_path?: string | null; readonly diagnostics?: ReadonlyArray<Diagnostic>; readonly ok: boolean; readonly project_revision?: string | null; readonly proposal?: ProjectProposal | null; readonly response_version?: number; };

export type ProposalListReport = { readonly canonical_path?: string | null; readonly diagnostics?: ReadonlyArray<Diagnostic>; readonly ok: boolean; readonly proposals?: ReadonlyArray<ProjectProposal>; readonly response_version?: number; };

export type DesktopContractName = "CheckResult" | "EngineHandshakeReport" | "HitTestReport" | "LayerTreeReport" | "PreviewProjectReport" | "ProjectPolicyReport" | "ProjectSnapshotReport" | "ProjectUIMetadataReport" | "ProposalActionReport" | "ProposalListReport";
export type DesktopContractGuard = (value: unknown) => boolean;

const desktopContractSchemas: Readonly<Record<DesktopContractName, JsonSchema>> = {
  "CheckResult": {
    "$defs": {
      "Diagnostic": {
        "description": "A single structured diagnostic.",
        "properties": {
          "code": {
            "title": "Code",
            "type": "string"
          },
          "hint": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Hint"
          },
          "message": {
            "title": "Message",
            "type": "string"
          },
          "severity": {
            "default": "error",
            "enum": [
              "error",
              "warning",
              "info"
            ],
            "title": "Severity",
            "type": "string"
          },
          "source": {
            "anyOf": [
              {
                "$ref": "#/$defs/SourceLocation"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          }
        },
        "required": [
          "code",
          "message"
        ],
        "title": "Diagnostic",
        "type": "object"
      },
      "SourceLocation": {
        "description": "A location in an authored source file.",
        "properties": {
          "column": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Column"
          },
          "file": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "File"
          },
          "keypath": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Keypath"
          },
          "line": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Line"
          }
        },
        "title": "SourceLocation",
        "type": "object"
      }
    },
    "description": "The result of ``arcavex template check``.",
    "properties": {
      "diagnostics": {
        "items": {
          "$ref": "#/$defs/Diagnostic"
        },
        "title": "Diagnostics",
        "type": "array"
      },
      "ok": {
        "title": "Ok",
        "type": "boolean"
      },
      "response_version": {
        "default": 1,
        "title": "Response Version",
        "type": "integer"
      }
    },
    "required": [
      "ok"
    ],
    "title": "CheckResult",
    "type": "object",
    "__filename": "project-validate.schema.json"
  },
  "EngineHandshakeReport": {
    "$defs": {
      "Diagnostic": {
        "description": "A single structured diagnostic.",
        "properties": {
          "code": {
            "title": "Code",
            "type": "string"
          },
          "hint": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Hint"
          },
          "message": {
            "title": "Message",
            "type": "string"
          },
          "severity": {
            "default": "error",
            "enum": [
              "error",
              "warning",
              "info"
            ],
            "title": "Severity",
            "type": "string"
          },
          "source": {
            "anyOf": [
              {
                "$ref": "#/$defs/SourceLocation"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          }
        },
        "required": [
          "code",
          "message"
        ],
        "title": "Diagnostic",
        "type": "object"
      },
      "DoctorCheck": {
        "description": "One environment probe result in a doctor report.",
        "properties": {
          "detail": {
            "title": "Detail",
            "type": "string"
          },
          "hint": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Hint"
          },
          "name": {
            "title": "Name",
            "type": "string"
          },
          "status": {
            "enum": [
              "ok",
              "warn",
              "fail"
            ],
            "title": "Status",
            "type": "string"
          }
        },
        "required": [
          "name",
          "status",
          "detail"
        ],
        "title": "DoctorCheck",
        "type": "object"
      },
      "DoctorReport": {
        "description": "The result of ``arcavex doctor``: engine version plus per-probe check rows.",
        "properties": {
          "checks": {
            "items": {
              "$ref": "#/$defs/DoctorCheck"
            },
            "title": "Checks",
            "type": "array"
          },
          "engine_version": {
            "title": "Engine Version",
            "type": "string"
          },
          "ok": {
            "title": "Ok",
            "type": "boolean"
          },
          "response_version": {
            "default": 1,
            "title": "Response Version",
            "type": "integer"
          }
        },
        "required": [
          "ok",
          "engine_version",
          "checks"
        ],
        "title": "DoctorReport",
        "type": "object"
      },
      "EngineIdentity": {
        "description": "Release identity for the executable serving a desktop client.",
        "properties": {
          "artifact_path": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Artifact Path"
          },
          "artifact_sha256": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Artifact Sha256"
          },
          "build_commit": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Build Commit"
          },
          "engine_version": {
            "title": "Engine Version",
            "type": "string"
          }
        },
        "required": [
          "engine_version"
        ],
        "title": "EngineIdentity",
        "type": "object"
      },
      "EnginePaths": {
        "description": "Arcavex home and the persistent stores rooted beneath it.",
        "properties": {
          "assets": {
            "title": "Assets",
            "type": "string"
          },
          "cache": {
            "title": "Cache",
            "type": "string"
          },
          "extensions": {
            "title": "Extensions",
            "type": "string"
          },
          "fonts": {
            "title": "Fonts",
            "type": "string"
          },
          "home": {
            "title": "Home",
            "type": "string"
          },
          "styles": {
            "title": "Styles",
            "type": "string"
          },
          "templates": {
            "title": "Templates",
            "type": "string"
          }
        },
        "required": [
          "home",
          "assets",
          "cache",
          "extensions",
          "fonts",
          "styles",
          "templates"
        ],
        "title": "EnginePaths",
        "type": "object"
      },
      "SourceLocation": {
        "description": "A location in an authored source file.",
        "properties": {
          "column": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Column"
          },
          "file": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "File"
          },
          "keypath": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Keypath"
          },
          "line": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Line"
          }
        },
        "title": "SourceLocation",
        "type": "object"
      }
    },
    "description": "Versioned startup contract shared by desktop CLI and MCP clients.",
    "properties": {
      "accepted_ir_versions": {
        "items": {
          "type": "string"
        },
        "title": "Accepted Ir Versions",
        "type": "array"
      },
      "capabilities": {
        "items": {
          "type": "string"
        },
        "title": "Capabilities",
        "type": "array"
      },
      "diagnostics": {
        "items": {
          "$ref": "#/$defs/Diagnostic"
        },
        "title": "Diagnostics",
        "type": "array"
      },
      "doctor": {
        "$ref": "#/$defs/DoctorReport"
      },
      "extension_sdk_version": {
        "title": "Extension Sdk Version",
        "type": "string"
      },
      "identity": {
        "$ref": "#/$defs/EngineIdentity"
      },
      "mcp_contract_version": {
        "title": "Mcp Contract Version",
        "type": "string"
      },
      "ok": {
        "title": "Ok",
        "type": "boolean"
      },
      "paths": {
        "$ref": "#/$defs/EnginePaths"
      },
      "produced_ir_version": {
        "title": "Produced Ir Version",
        "type": "string"
      },
      "response_version": {
        "default": 1,
        "title": "Response Version",
        "type": "integer"
      }
    },
    "required": [
      "ok",
      "identity",
      "mcp_contract_version",
      "accepted_ir_versions",
      "produced_ir_version",
      "extension_sdk_version",
      "capabilities",
      "paths",
      "doctor"
    ],
    "title": "EngineHandshakeReport",
    "type": "object",
    "__filename": "engine-handshake.schema.json"
  },
  "HitTestReport": {
    "$defs": {
      "Diagnostic": {
        "description": "A single structured diagnostic.",
        "properties": {
          "code": {
            "title": "Code",
            "type": "string"
          },
          "hint": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Hint"
          },
          "message": {
            "title": "Message",
            "type": "string"
          },
          "severity": {
            "default": "error",
            "enum": [
              "error",
              "warning",
              "info"
            ],
            "title": "Severity",
            "type": "string"
          },
          "source": {
            "anyOf": [
              {
                "$ref": "#/$defs/SourceLocation"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          }
        },
        "required": [
          "code",
          "message"
        ],
        "title": "Diagnostic",
        "type": "object"
      },
      "HitCandidate": {
        "description": "One rendered layer whose paint bounds contain the queried canvas point.",
        "properties": {
          "authored_id": {
            "title": "Authored Id",
            "type": "string"
          },
          "bounds_pt": {
            "maxItems": 4,
            "minItems": 4,
            "prefixItems": [
              {
                "type": "number"
              },
              {
                "type": "number"
              },
              {
                "type": "number"
              },
              {
                "type": "number"
              }
            ],
            "title": "Bounds Pt",
            "type": "array"
          },
          "display_name": {
            "title": "Display Name",
            "type": "string"
          },
          "editable": {
            "title": "Editable",
            "type": "boolean"
          },
          "id": {
            "title": "Id",
            "type": "string"
          },
          "instance_id": {
            "title": "Instance Id",
            "type": "string"
          },
          "kind": {
            "enum": [
              "group",
              "text",
              "image",
              "shape",
              "path"
            ],
            "title": "Kind",
            "type": "string"
          },
          "locked": {
            "title": "Locked",
            "type": "boolean"
          },
          "paint_bounds_pt": {
            "maxItems": 4,
            "minItems": 4,
            "prefixItems": [
              {
                "type": "number"
              },
              {
                "type": "number"
              },
              {
                "type": "number"
              },
              {
                "type": "number"
              }
            ],
            "title": "Paint Bounds Pt",
            "type": "array"
          },
          "parent_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Parent Id"
          }
        },
        "required": [
          "id",
          "authored_id",
          "instance_id",
          "kind",
          "display_name",
          "editable",
          "locked",
          "bounds_pt",
          "paint_bounds_pt"
        ],
        "title": "HitCandidate",
        "type": "object"
      },
      "SourceLocation": {
        "description": "A location in an authored source file.",
        "properties": {
          "column": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Column"
          },
          "file": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "File"
          },
          "keypath": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Keypath"
          },
          "line": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Line"
          }
        },
        "title": "SourceLocation",
        "type": "object"
      }
    },
    "description": "Topmost-first geometry hit-test result in canonical canvas point space.",
    "properties": {
      "candidates": {
        "items": {
          "$ref": "#/$defs/HitCandidate"
        },
        "title": "Candidates",
        "type": "array"
      },
      "diagnostics": {
        "items": {
          "$ref": "#/$defs/Diagnostic"
        },
        "title": "Diagnostics",
        "type": "array"
      },
      "format": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Format"
      },
      "locale": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Locale"
      },
      "ok": {
        "title": "Ok",
        "type": "boolean"
      },
      "point_pt": {
        "default": [
          0,
          0
        ],
        "maxItems": 2,
        "minItems": 2,
        "prefixItems": [
          {
            "type": "number"
          },
          {
            "type": "number"
          }
        ],
        "title": "Point Pt",
        "type": "array"
      },
      "point_px": {
        "anyOf": [
          {
            "maxItems": 2,
            "minItems": 2,
            "prefixItems": [
              {
                "type": "number"
              },
              {
                "type": "number"
              }
            ],
            "type": "array"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Point Px"
      },
      "response_version": {
        "default": 1,
        "title": "Response Version",
        "type": "integer"
      }
    },
    "required": [
      "ok"
    ],
    "title": "HitTestReport",
    "type": "object",
    "__filename": "hit-test.schema.json"
  },
  "LayerTreeReport": {
    "$defs": {
      "Diagnostic": {
        "description": "A single structured diagnostic.",
        "properties": {
          "code": {
            "title": "Code",
            "type": "string"
          },
          "hint": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Hint"
          },
          "message": {
            "title": "Message",
            "type": "string"
          },
          "severity": {
            "default": "error",
            "enum": [
              "error",
              "warning",
              "info"
            ],
            "title": "Severity",
            "type": "string"
          },
          "source": {
            "anyOf": [
              {
                "$ref": "#/$defs/SourceLocation"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          }
        },
        "required": [
          "code",
          "message"
        ],
        "title": "Diagnostic",
        "type": "object"
      },
      "LayerEffect": {
        "description": "One resolved effect declaration attached to a layer.",
        "properties": {
          "category": {
            "anyOf": [
              {
                "enum": [
                  "geometry",
                  "color",
                  "raster",
                  "composite"
                ],
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Category"
          },
          "index": {
            "title": "Index",
            "type": "integer"
          },
          "name": {
            "title": "Name",
            "type": "string"
          },
          "params": {
            "additionalProperties": true,
            "title": "Params",
            "type": "object"
          }
        },
        "required": [
          "index",
          "name"
        ],
        "title": "LayerEffect",
        "type": "object"
      },
      "LayerMask": {
        "description": "One resolved mask declaration attached to a layer.",
        "properties": {
          "component": {
            "title": "Component",
            "type": "string"
          },
          "params": {
            "additionalProperties": true,
            "title": "Params",
            "type": "object"
          }
        },
        "required": [
          "component"
        ],
        "title": "LayerMask",
        "type": "object"
      },
      "LayerNodeReport": {
        "description": "One definition, rendered instance, or virtual effect/mask row in a layer tree.",
        "properties": {
          "absolute_transform": {
            "anyOf": [
              {
                "maxItems": 6,
                "minItems": 6,
                "prefixItems": [
                  {
                    "type": "number"
                  },
                  {
                    "type": "number"
                  },
                  {
                    "type": "number"
                  },
                  {
                    "type": "number"
                  },
                  {
                    "type": "number"
                  },
                  {
                    "type": "number"
                  }
                ],
                "type": "array"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Absolute Transform"
          },
          "authored_id": {
            "title": "Authored Id",
            "type": "string"
          },
          "authored_index": {
            "title": "Authored Index",
            "type": "integer"
          },
          "bounds_pt": {
            "anyOf": [
              {
                "maxItems": 4,
                "minItems": 4,
                "prefixItems": [
                  {
                    "type": "number"
                  },
                  {
                    "type": "number"
                  },
                  {
                    "type": "number"
                  },
                  {
                    "type": "number"
                  }
                ],
                "type": "array"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Bounds Pt"
          },
          "bounds_px": {
            "anyOf": [
              {
                "maxItems": 4,
                "minItems": 4,
                "prefixItems": [
                  {
                    "type": "number"
                  },
                  {
                    "type": "number"
                  },
                  {
                    "type": "number"
                  },
                  {
                    "type": "number"
                  }
                ],
                "type": "array"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Bounds Px"
          },
          "children": {
            "items": {
              "$ref": "#/$defs/LayerNodeReport"
            },
            "title": "Children",
            "type": "array"
          },
          "collection": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Collection"
          },
          "color": {
            "anyOf": [
              {
                "pattern": "^#[0-9A-Fa-f]{6}$",
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Color"
          },
          "condition": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Condition"
          },
          "display_name": {
            "title": "Display Name",
            "type": "string"
          },
          "editable": {
            "default": true,
            "title": "Editable",
            "type": "boolean"
          },
          "effects": {
            "items": {
              "$ref": "#/$defs/LayerEffect"
            },
            "title": "Effects",
            "type": "array"
          },
          "hit_testable": {
            "default": true,
            "title": "Hit Testable",
            "type": "boolean"
          },
          "id": {
            "title": "Id",
            "type": "string"
          },
          "instance_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Instance Id"
          },
          "key": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Key"
          },
          "kind": {
            "title": "Kind",
            "type": "string"
          },
          "locked": {
            "default": false,
            "title": "Locked",
            "type": "boolean"
          },
          "loop_var": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Loop Var"
          },
          "mask": {
            "anyOf": [
              {
                "$ref": "#/$defs/LayerMask"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          },
          "origin": {
            "default": "static",
            "enum": [
              "static",
              "repeat",
              "if"
            ],
            "title": "Origin",
            "type": "string"
          },
          "overflow": {
            "anyOf": [
              {
                "$ref": "#/$defs/OverflowReport"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          },
          "paint_bounds_pt": {
            "anyOf": [
              {
                "maxItems": 4,
                "minItems": 4,
                "prefixItems": [
                  {
                    "type": "number"
                  },
                  {
                    "type": "number"
                  },
                  {
                    "type": "number"
                  },
                  {
                    "type": "number"
                  }
                ],
                "type": "array"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Paint Bounds Pt"
          },
          "paint_bounds_px": {
            "anyOf": [
              {
                "maxItems": 4,
                "minItems": 4,
                "prefixItems": [
                  {
                    "type": "number"
                  },
                  {
                    "type": "number"
                  },
                  {
                    "type": "number"
                  },
                  {
                    "type": "number"
                  }
                ],
                "type": "array"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Paint Bounds Px"
          },
          "paint_index": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Paint Index"
          },
          "parent_id": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Parent Id"
          },
          "rotate_deg": {
            "default": 0,
            "title": "Rotate Deg",
            "type": "number"
          },
          "source": {
            "anyOf": [
              {
                "$ref": "#/$defs/LayerSource"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          },
          "virtual": {
            "default": false,
            "title": "Virtual",
            "type": "boolean"
          },
          "visible": {
            "default": true,
            "title": "Visible",
            "type": "boolean"
          },
          "z": {
            "default": 0,
            "title": "Z",
            "type": "integer"
          }
        },
        "required": [
          "id",
          "authored_id",
          "authored_index",
          "kind",
          "display_name"
        ],
        "title": "LayerNodeReport",
        "type": "object"
      },
      "LayerSource": {
        "description": "Stable authoring location for a layer definition.",
        "properties": {
          "file": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "File"
          },
          "keypath": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Keypath"
          },
          "line": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Line"
          }
        },
        "title": "LayerSource",
        "type": "object"
      },
      "OverflowReport": {
        "description": "A node's text-overflow outcome, echoed for inspection.",
        "properties": {
          "box_h_pt": {
            "title": "Box H Pt",
            "type": "number"
          },
          "box_w_pt": {
            "title": "Box W Pt",
            "type": "number"
          },
          "kind": {
            "title": "Kind",
            "type": "string"
          },
          "measured_h_pt": {
            "title": "Measured H Pt",
            "type": "number"
          },
          "measured_w_pt": {
            "title": "Measured W Pt",
            "type": "number"
          }
        },
        "required": [
          "kind",
          "measured_w_pt",
          "measured_h_pt",
          "box_w_pt",
          "box_h_pt"
        ],
        "title": "OverflowReport",
        "type": "object"
      },
      "SourceLocation": {
        "description": "A location in an authored source file.",
        "properties": {
          "column": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Column"
          },
          "file": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "File"
          },
          "keypath": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Keypath"
          },
          "line": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Line"
          }
        },
        "title": "SourceLocation",
        "type": "object"
      }
    },
    "description": "Authoritative desktop layer hierarchy in authored or rendered mode.",
    "properties": {
      "canvas_pt": {
        "default": [
          0,
          0
        ],
        "maxItems": 2,
        "minItems": 2,
        "prefixItems": [
          {
            "type": "number"
          },
          {
            "type": "number"
          }
        ],
        "title": "Canvas Pt",
        "type": "array"
      },
      "canvas_px": {
        "default": [
          0,
          0
        ],
        "maxItems": 2,
        "minItems": 2,
        "prefixItems": [
          {
            "type": "integer"
          },
          {
            "type": "integer"
          }
        ],
        "title": "Canvas Px",
        "type": "array"
      },
      "diagnostics": {
        "items": {
          "$ref": "#/$defs/Diagnostic"
        },
        "title": "Diagnostics",
        "type": "array"
      },
      "dpi": {
        "default": 0,
        "title": "Dpi",
        "type": "integer"
      },
      "format": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Format"
      },
      "locale": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Locale"
      },
      "mode": {
        "default": "authored",
        "enum": [
          "authored",
          "rendered"
        ],
        "title": "Mode",
        "type": "string"
      },
      "ok": {
        "title": "Ok",
        "type": "boolean"
      },
      "response_version": {
        "default": 1,
        "title": "Response Version",
        "type": "integer"
      },
      "root": {
        "anyOf": [
          {
            "$ref": "#/$defs/LayerNodeReport"
          },
          {
            "type": "null"
          }
        ],
        "default": null
      }
    },
    "required": [
      "ok"
    ],
    "title": "LayerTreeReport",
    "type": "object",
    "__filename": "layer-tree.schema.json"
  },
  "PreviewProjectReport": {
    "$defs": {
      "Diagnostic": {
        "description": "A single structured diagnostic.",
        "properties": {
          "code": {
            "title": "Code",
            "type": "string"
          },
          "hint": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Hint"
          },
          "message": {
            "title": "Message",
            "type": "string"
          },
          "severity": {
            "default": "error",
            "enum": [
              "error",
              "warning",
              "info"
            ],
            "title": "Severity",
            "type": "string"
          },
          "source": {
            "anyOf": [
              {
                "$ref": "#/$defs/SourceLocation"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          }
        },
        "required": [
          "code",
          "message"
        ],
        "title": "Diagnostic",
        "type": "object"
      },
      "PreviewResult": {
        "description": "The result of a single ``arcavex preview`` render (watch or one-shot).",
        "properties": {
          "changed_file": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Changed File"
          },
          "compile_ms": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Compile Ms"
          },
          "content_sha256": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Content Sha256"
          },
          "diagnostics": {
            "items": {
              "$ref": "#/$defs/Diagnostic"
            },
            "title": "Diagnostics",
            "type": "array"
          },
          "inferred": {
            "additionalProperties": {
              "type": "string"
            },
            "title": "Inferred",
            "type": "object"
          },
          "ok": {
            "title": "Ok",
            "type": "boolean"
          },
          "output_path": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Output Path"
          },
          "render_ms": {
            "anyOf": [
              {
                "type": "number"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Render Ms"
          },
          "response_version": {
            "default": 1,
            "title": "Response Version",
            "type": "integer"
          }
        },
        "required": [
          "ok"
        ],
        "title": "PreviewResult",
        "type": "object"
      },
      "SourceLocation": {
        "description": "A location in an authored source file.",
        "properties": {
          "column": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Column"
          },
          "file": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "File"
          },
          "keypath": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Keypath"
          },
          "line": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Line"
          }
        },
        "title": "SourceLocation",
        "type": "object"
      }
    },
    "description": "The result of ``arcavex preview`` in project mode: one preview per format × locale (DX-1).",
    "properties": {
      "diagnostics": {
        "items": {
          "$ref": "#/$defs/Diagnostic"
        },
        "title": "Diagnostics",
        "type": "array"
      },
      "ok": {
        "title": "Ok",
        "type": "boolean"
      },
      "previews": {
        "items": {
          "$ref": "#/$defs/PreviewResult"
        },
        "title": "Previews",
        "type": "array"
      },
      "response_version": {
        "default": 1,
        "title": "Response Version",
        "type": "integer"
      }
    },
    "required": [
      "ok"
    ],
    "title": "PreviewProjectReport",
    "type": "object",
    "__filename": "project-preview.schema.json"
  },
  "ProjectPolicyReport": {
    "$defs": {
      "AutomationPolicy": {
        "additionalProperties": false,
        "description": "Versioned project-local policy for semantic automation and extension execution.",
        "properties": {
          "extensions": {
            "default": "unrestricted",
            "enum": [
              "unrestricted",
              "disabled"
            ],
            "title": "Extensions",
            "type": "string"
          },
          "mode": {
            "default": "unrestricted",
            "enum": [
              "unrestricted",
              "review",
              "read_only"
            ],
            "title": "Mode",
            "type": "string"
          },
          "version": {
            "const": 1,
            "default": 1,
            "title": "Version",
            "type": "integer"
          }
        },
        "title": "AutomationPolicy",
        "type": "object"
      },
      "Diagnostic": {
        "description": "A single structured diagnostic.",
        "properties": {
          "code": {
            "title": "Code",
            "type": "string"
          },
          "hint": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Hint"
          },
          "message": {
            "title": "Message",
            "type": "string"
          },
          "severity": {
            "default": "error",
            "enum": [
              "error",
              "warning",
              "info"
            ],
            "title": "Severity",
            "type": "string"
          },
          "source": {
            "anyOf": [
              {
                "$ref": "#/$defs/SourceLocation"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          }
        },
        "required": [
          "code",
          "message"
        ],
        "title": "Diagnostic",
        "type": "object"
      },
      "SourceLocation": {
        "description": "A location in an authored source file.",
        "properties": {
          "column": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Column"
          },
          "file": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "File"
          },
          "keypath": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Keypath"
          },
          "line": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Line"
          }
        },
        "title": "SourceLocation",
        "type": "object"
      }
    },
    "description": "Current project policy together with the revisions that govern it.",
    "properties": {
      "canonical_path": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Canonical Path"
      },
      "diagnostics": {
        "items": {
          "$ref": "#/$defs/Diagnostic"
        },
        "title": "Diagnostics",
        "type": "array"
      },
      "ok": {
        "title": "Ok",
        "type": "boolean"
      },
      "policy": {
        "$ref": "#/$defs/AutomationPolicy"
      },
      "project_revision": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Project Revision"
      },
      "render_revision": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Render Revision"
      },
      "response_version": {
        "default": 1,
        "title": "Response Version",
        "type": "integer"
      }
    },
    "required": [
      "ok"
    ],
    "title": "ProjectPolicyReport",
    "type": "object",
    "__filename": "project-policy.schema.json"
  },
  "ProjectSnapshotReport": {
    "$defs": {
      "Diagnostic": {
        "description": "A single structured diagnostic.",
        "properties": {
          "code": {
            "title": "Code",
            "type": "string"
          },
          "hint": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Hint"
          },
          "message": {
            "title": "Message",
            "type": "string"
          },
          "severity": {
            "default": "error",
            "enum": [
              "error",
              "warning",
              "info"
            ],
            "title": "Severity",
            "type": "string"
          },
          "source": {
            "anyOf": [
              {
                "$ref": "#/$defs/SourceLocation"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          }
        },
        "required": [
          "code",
          "message"
        ],
        "title": "Diagnostic",
        "type": "object"
      },
      "ProjectSourceFile": {
        "description": "A project input and its resolved source location for conflict diagnostics.",
        "properties": {
          "path": {
            "title": "Path",
            "type": "string"
          },
          "project_owned": {
            "title": "Project Owned",
            "type": "boolean"
          },
          "resolved_path": {
            "title": "Resolved Path",
            "type": "string"
          },
          "role": {
            "enum": [
              "project",
              "ui",
              "template",
              "data",
              "override",
              "asset"
            ],
            "title": "Role",
            "type": "string"
          },
          "sha256": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Sha256"
          }
        },
        "required": [
          "path",
          "resolved_path",
          "role",
          "project_owned"
        ],
        "title": "ProjectSourceFile",
        "type": "object"
      },
      "ProjectTarget": {
        "description": "One deterministic format and locale combination declared by a project.",
        "properties": {
          "format": {
            "title": "Format",
            "type": "string"
          },
          "locale": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Locale"
          }
        },
        "required": [
          "format"
        ],
        "title": "ProjectTarget",
        "type": "object"
      },
      "RevisionManifestEntry": {
        "description": "One normalized file or synthetic projection participating in a revision.",
        "properties": {
          "bytes": {
            "title": "Bytes",
            "type": "integer"
          },
          "path": {
            "title": "Path",
            "type": "string"
          },
          "sha256": {
            "title": "Sha256",
            "type": "string"
          }
        },
        "required": [
          "path",
          "sha256",
          "bytes"
        ],
        "title": "RevisionManifestEntry",
        "type": "object"
      },
      "SourceLocation": {
        "description": "A location in an authored source file.",
        "properties": {
          "column": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Column"
          },
          "file": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "File"
          },
          "keypath": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Keypath"
          },
          "line": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Line"
          }
        },
        "title": "SourceLocation",
        "type": "object"
      }
    },
    "description": "Read-only desktop snapshot with independent project and render revisions.",
    "properties": {
      "canonical_path": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Canonical Path"
      },
      "capabilities": {
        "items": {
          "type": "string"
        },
        "title": "Capabilities",
        "type": "array"
      },
      "data": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Data"
      },
      "default_target": {
        "anyOf": [
          {
            "$ref": "#/$defs/ProjectTarget"
          },
          {
            "type": "null"
          }
        ],
        "default": null
      },
      "diagnostics": {
        "items": {
          "$ref": "#/$defs/Diagnostic"
        },
        "title": "Diagnostics",
        "type": "array"
      },
      "dpi": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Dpi"
      },
      "formats": {
        "items": {
          "type": "string"
        },
        "title": "Formats",
        "type": "array"
      },
      "locales": {
        "items": {
          "type": "string"
        },
        "title": "Locales",
        "type": "array"
      },
      "name": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Name"
      },
      "ok": {
        "title": "Ok",
        "type": "boolean"
      },
      "project_manifest": {
        "items": {
          "$ref": "#/$defs/RevisionManifestEntry"
        },
        "title": "Project Manifest",
        "type": "array"
      },
      "project_revision": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Project Revision"
      },
      "render_manifest": {
        "items": {
          "$ref": "#/$defs/RevisionManifestEntry"
        },
        "title": "Render Manifest",
        "type": "array"
      },
      "render_revision": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Render Revision"
      },
      "response_version": {
        "default": 1,
        "title": "Response Version",
        "type": "integer"
      },
      "source_files": {
        "items": {
          "$ref": "#/$defs/ProjectSourceFile"
        },
        "title": "Source Files",
        "type": "array"
      },
      "status": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Status"
      },
      "style": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Style"
      },
      "tags": {
        "items": {
          "type": "string"
        },
        "title": "Tags",
        "type": "array"
      },
      "targets": {
        "items": {
          "$ref": "#/$defs/ProjectTarget"
        },
        "title": "Targets",
        "type": "array"
      },
      "template": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Template"
      }
    },
    "required": [
      "ok"
    ],
    "title": "ProjectSnapshotReport",
    "type": "object",
    "__filename": "project-snapshot.schema.json"
  },
  "ProjectUIMetadataReport": {
    "$defs": {
      "Diagnostic": {
        "description": "A single structured diagnostic.",
        "properties": {
          "code": {
            "title": "Code",
            "type": "string"
          },
          "hint": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Hint"
          },
          "message": {
            "title": "Message",
            "type": "string"
          },
          "severity": {
            "default": "error",
            "enum": [
              "error",
              "warning",
              "info"
            ],
            "title": "Severity",
            "type": "string"
          },
          "source": {
            "anyOf": [
              {
                "$ref": "#/$defs/SourceLocation"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          }
        },
        "required": [
          "code",
          "message"
        ],
        "title": "Diagnostic",
        "type": "object"
      },
      "LayerUIMetadata": {
        "additionalProperties": false,
        "description": "Non-rendering editor metadata for one stable authored layer ID.",
        "properties": {
          "color": {
            "anyOf": [
              {
                "pattern": "^#[0-9A-Fa-f]{6}$",
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Color"
          },
          "display_name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Display Name"
          },
          "locked": {
            "default": false,
            "title": "Locked",
            "type": "boolean"
          }
        },
        "title": "LayerUIMetadata",
        "type": "object"
      },
      "ProjectUIMetadata": {
        "additionalProperties": false,
        "description": "Versioned contents of the optional non-rendering ``project.ui.yaml`` sidecar.",
        "properties": {
          "layers": {
            "additionalProperties": {
              "$ref": "#/$defs/LayerUIMetadata"
            },
            "title": "Layers",
            "type": "object"
          },
          "version": {
            "const": 1,
            "default": 1,
            "title": "Version",
            "type": "integer"
          },
          "workspace": {
            "$ref": "#/$defs/ProjectWorkspaceState"
          }
        },
        "title": "ProjectUIMetadata",
        "type": "object"
      },
      "ProjectWorkspaceState": {
        "additionalProperties": false,
        "description": "Project-local workspace choices that may travel with the authored project.",
        "properties": {
          "active_format": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Active Format"
          },
          "active_locale": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Active Locale"
          },
          "layer_tree_mode": {
            "default": "definition",
            "enum": [
              "definition",
              "rendered"
            ],
            "title": "Layer Tree Mode",
            "type": "string"
          },
          "selected_layer_ids": {
            "items": {
              "type": "string"
            },
            "title": "Selected Layer Ids",
            "type": "array"
          }
        },
        "title": "ProjectWorkspaceState",
        "type": "object"
      },
      "SourceLocation": {
        "description": "A location in an authored source file.",
        "properties": {
          "column": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Column"
          },
          "file": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "File"
          },
          "keypath": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Keypath"
          },
          "line": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Line"
          }
        },
        "title": "SourceLocation",
        "type": "object"
      }
    },
    "description": "Current editor metadata together with the revisions that govern it.",
    "properties": {
      "canonical_path": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Canonical Path"
      },
      "diagnostics": {
        "items": {
          "$ref": "#/$defs/Diagnostic"
        },
        "title": "Diagnostics",
        "type": "array"
      },
      "metadata": {
        "$ref": "#/$defs/ProjectUIMetadata"
      },
      "ok": {
        "title": "Ok",
        "type": "boolean"
      },
      "project_revision": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Project Revision"
      },
      "render_revision": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Render Revision"
      },
      "response_version": {
        "default": 1,
        "title": "Response Version",
        "type": "integer"
      }
    },
    "required": [
      "ok"
    ],
    "title": "ProjectUIMetadataReport",
    "type": "object",
    "__filename": "project-ui-metadata.schema.json"
  },
  "ProposalActionReport": {
    "$defs": {
      "Diagnostic": {
        "description": "A single structured diagnostic.",
        "properties": {
          "code": {
            "title": "Code",
            "type": "string"
          },
          "hint": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Hint"
          },
          "message": {
            "title": "Message",
            "type": "string"
          },
          "severity": {
            "default": "error",
            "enum": [
              "error",
              "warning",
              "info"
            ],
            "title": "Severity",
            "type": "string"
          },
          "source": {
            "anyOf": [
              {
                "$ref": "#/$defs/SourceLocation"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          }
        },
        "required": [
          "code",
          "message"
        ],
        "title": "Diagnostic",
        "type": "object"
      },
      "ProjectProposal": {
        "additionalProperties": false,
        "description": "Versioned queue record for a future semantic editor command.",
        "properties": {
          "actor": {
            "$ref": "#/$defs/ProposalActor"
          },
          "base_project_revision": {
            "pattern": "^[0-9a-f]{64}$",
            "title": "Base Project Revision",
            "type": "string"
          },
          "command_id": {
            "format": "uuid4",
            "title": "Command Id",
            "type": "string"
          },
          "command_payload": {
            "additionalProperties": true,
            "title": "Command Payload",
            "type": "object"
          },
          "created_at": {
            "format": "date-time",
            "title": "Created At",
            "type": "string"
          },
          "project_path": {
            "title": "Project Path",
            "type": "string"
          },
          "rejection_reason": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Rejection Reason"
          },
          "state": {
            "default": "pending",
            "enum": [
              "pending",
              "authorized",
              "rejected"
            ],
            "title": "State",
            "type": "string"
          },
          "version": {
            "const": 1,
            "default": 1,
            "title": "Version",
            "type": "integer"
          }
        },
        "required": [
          "command_id",
          "project_path",
          "base_project_revision",
          "actor",
          "command_payload",
          "created_at"
        ],
        "title": "ProjectProposal",
        "type": "object"
      },
      "ProposalActor": {
        "additionalProperties": true,
        "description": "Identity attached to a queued semantic command proposal.",
        "properties": {
          "display_name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Display Name"
          },
          "id": {
            "minLength": 1,
            "title": "Id",
            "type": "string"
          }
        },
        "required": [
          "id"
        ],
        "title": "ProposalActor",
        "type": "object"
      },
      "SourceLocation": {
        "description": "A location in an authored source file.",
        "properties": {
          "column": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Column"
          },
          "file": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "File"
          },
          "keypath": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Keypath"
          },
          "line": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Line"
          }
        },
        "title": "SourceLocation",
        "type": "object"
      }
    },
    "description": "Result of authorizing or rejecting one proposal; no command execution is implied.",
    "properties": {
      "canonical_path": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Canonical Path"
      },
      "diagnostics": {
        "items": {
          "$ref": "#/$defs/Diagnostic"
        },
        "title": "Diagnostics",
        "type": "array"
      },
      "ok": {
        "title": "Ok",
        "type": "boolean"
      },
      "project_revision": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Project Revision"
      },
      "proposal": {
        "anyOf": [
          {
            "$ref": "#/$defs/ProjectProposal"
          },
          {
            "type": "null"
          }
        ],
        "default": null
      },
      "response_version": {
        "default": 1,
        "title": "Response Version",
        "type": "integer"
      }
    },
    "required": [
      "ok"
    ],
    "title": "ProposalActionReport",
    "type": "object",
    "__filename": "project-proposal-action.schema.json"
  },
  "ProposalListReport": {
    "$defs": {
      "Diagnostic": {
        "description": "A single structured diagnostic.",
        "properties": {
          "code": {
            "title": "Code",
            "type": "string"
          },
          "hint": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Hint"
          },
          "message": {
            "title": "Message",
            "type": "string"
          },
          "severity": {
            "default": "error",
            "enum": [
              "error",
              "warning",
              "info"
            ],
            "title": "Severity",
            "type": "string"
          },
          "source": {
            "anyOf": [
              {
                "$ref": "#/$defs/SourceLocation"
              },
              {
                "type": "null"
              }
            ],
            "default": null
          }
        },
        "required": [
          "code",
          "message"
        ],
        "title": "Diagnostic",
        "type": "object"
      },
      "ProjectProposal": {
        "additionalProperties": false,
        "description": "Versioned queue record for a future semantic editor command.",
        "properties": {
          "actor": {
            "$ref": "#/$defs/ProposalActor"
          },
          "base_project_revision": {
            "pattern": "^[0-9a-f]{64}$",
            "title": "Base Project Revision",
            "type": "string"
          },
          "command_id": {
            "format": "uuid4",
            "title": "Command Id",
            "type": "string"
          },
          "command_payload": {
            "additionalProperties": true,
            "title": "Command Payload",
            "type": "object"
          },
          "created_at": {
            "format": "date-time",
            "title": "Created At",
            "type": "string"
          },
          "project_path": {
            "title": "Project Path",
            "type": "string"
          },
          "rejection_reason": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Rejection Reason"
          },
          "state": {
            "default": "pending",
            "enum": [
              "pending",
              "authorized",
              "rejected"
            ],
            "title": "State",
            "type": "string"
          },
          "version": {
            "const": 1,
            "default": 1,
            "title": "Version",
            "type": "integer"
          }
        },
        "required": [
          "command_id",
          "project_path",
          "base_project_revision",
          "actor",
          "command_payload",
          "created_at"
        ],
        "title": "ProjectProposal",
        "type": "object"
      },
      "ProposalActor": {
        "additionalProperties": true,
        "description": "Identity attached to a queued semantic command proposal.",
        "properties": {
          "display_name": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Display Name"
          },
          "id": {
            "minLength": 1,
            "title": "Id",
            "type": "string"
          }
        },
        "required": [
          "id"
        ],
        "title": "ProposalActor",
        "type": "object"
      },
      "SourceLocation": {
        "description": "A location in an authored source file.",
        "properties": {
          "column": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Column"
          },
          "file": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "File"
          },
          "keypath": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Keypath"
          },
          "line": {
            "anyOf": [
              {
                "type": "integer"
              },
              {
                "type": "null"
              }
            ],
            "default": null,
            "title": "Line"
          }
        },
        "title": "SourceLocation",
        "type": "object"
      }
    },
    "description": "Deterministically ordered proposals plus diagnostics for unreadable entries.",
    "properties": {
      "canonical_path": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ],
        "default": null,
        "title": "Canonical Path"
      },
      "diagnostics": {
        "items": {
          "$ref": "#/$defs/Diagnostic"
        },
        "title": "Diagnostics",
        "type": "array"
      },
      "ok": {
        "title": "Ok",
        "type": "boolean"
      },
      "proposals": {
        "items": {
          "$ref": "#/$defs/ProjectProposal"
        },
        "title": "Proposals",
        "type": "array"
      },
      "response_version": {
        "default": 1,
        "title": "Response Version",
        "type": "integer"
      }
    },
    "required": [
      "ok"
    ],
    "title": "ProposalListReport",
    "type": "object",
    "__filename": "project-proposal-list.schema.json"
  }
} as unknown as Readonly<Record<DesktopContractName, JsonSchema>>;

export const desktopContractNames = ["CheckResult", "EngineHandshakeReport", "HitTestReport", "LayerTreeReport", "PreviewProjectReport", "ProjectPolicyReport", "ProjectSnapshotReport", "ProjectUIMetadataReport", "ProposalActionReport", "ProposalListReport"] as const satisfies ReadonlyArray<DesktopContractName>;

export const desktopContractFixtures: Readonly<Record<DesktopContractName, Readonly<Record<string, unknown>>>> = {
  "CheckResult": {
    "diagnostics": [],
    "ok": true,
    "response_version": 1
  },
  "EngineHandshakeReport": {
    "accepted_ir_versions": [
      "1.0"
    ],
    "capabilities": [],
    "diagnostics": [],
    "doctor": {
      "checks": [],
      "engine_version": "0.0.0-fixture",
      "ok": true,
      "response_version": 1
    },
    "extension_sdk_version": "1.0",
    "identity": {
      "artifact_path": null,
      "artifact_sha256": null,
      "build_commit": null,
      "engine_version": "0.0.0-fixture"
    },
    "mcp_contract_version": "2025-06-18",
    "ok": true,
    "paths": {
      "assets": "/fixture/assets",
      "cache": "/fixture/cache",
      "extensions": "/fixture/extensions",
      "fonts": "/fixture/fonts",
      "home": "/fixture",
      "styles": "/fixture/styles",
      "templates": "/fixture/templates"
    },
    "produced_ir_version": "1.0",
    "response_version": 1
  },
  "HitTestReport": {
    "candidates": [],
    "diagnostics": [],
    "format": null,
    "locale": null,
    "ok": true,
    "point_pt": [
      0,
      0
    ],
    "point_px": null,
    "response_version": 1
  },
  "LayerTreeReport": {
    "canvas_pt": [
      0,
      0
    ],
    "canvas_px": [
      0,
      0
    ],
    "diagnostics": [],
    "dpi": 0,
    "format": null,
    "locale": null,
    "mode": "authored",
    "ok": true,
    "response_version": 1,
    "root": null
  },
  "PreviewProjectReport": {
    "diagnostics": [],
    "ok": true,
    "previews": [],
    "response_version": 1
  },
  "ProjectPolicyReport": {
    "canonical_path": null,
    "diagnostics": [],
    "ok": true,
    "policy": {
      "extensions": "unrestricted",
      "mode": "unrestricted",
      "version": 1
    },
    "project_revision": null,
    "render_revision": null,
    "response_version": 1
  },
  "ProjectSnapshotReport": {
    "canonical_path": null,
    "capabilities": [],
    "data": null,
    "default_target": null,
    "diagnostics": [],
    "dpi": null,
    "formats": [],
    "locales": [],
    "name": null,
    "ok": true,
    "project_manifest": [],
    "project_revision": null,
    "render_manifest": [],
    "render_revision": null,
    "response_version": 1,
    "source_files": [],
    "status": null,
    "style": null,
    "tags": [],
    "targets": [],
    "template": null
  },
  "ProjectUIMetadataReport": {
    "canonical_path": null,
    "diagnostics": [],
    "metadata": {
      "layers": {},
      "version": 1,
      "workspace": {
        "active_format": null,
        "active_locale": null,
        "layer_tree_mode": "definition",
        "selected_layer_ids": []
      }
    },
    "ok": true,
    "project_revision": null,
    "render_revision": null,
    "response_version": 1
  },
  "ProposalActionReport": {
    "canonical_path": null,
    "diagnostics": [],
    "ok": true,
    "project_revision": null,
    "proposal": null,
    "response_version": 1
  },
  "ProposalListReport": {
    "canonical_path": null,
    "diagnostics": [],
    "ok": true,
    "proposals": [],
    "response_version": 1
  }
} as Readonly<Record<DesktopContractName, Readonly<Record<string, unknown>>>>;

type JsonSchema = boolean | {
  readonly $defs?: Readonly<Record<string, JsonSchema>>;
  readonly $ref?: string;
  readonly allOf?: ReadonlyArray<JsonSchema>;
  readonly anyOf?: ReadonlyArray<JsonSchema>;
  readonly oneOf?: ReadonlyArray<JsonSchema>;
  readonly const?: unknown;
  readonly enum?: ReadonlyArray<unknown>;
  readonly type?: string | ReadonlyArray<string>;
  readonly required?: ReadonlyArray<string>;
  readonly properties?: Readonly<Record<string, JsonSchema>>;
  readonly additionalProperties?: JsonSchema;
  readonly items?: JsonSchema;
  readonly prefixItems?: ReadonlyArray<JsonSchema>;
  readonly minLength?: number;
  readonly maxLength?: number;
  readonly minimum?: number;
  readonly maximum?: number;
  readonly exclusiveMinimum?: number;
  readonly exclusiveMaximum?: number;
  readonly minItems?: number;
  readonly maxItems?: number;
};

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function resolveReference(reference: string, root: JsonSchema): JsonSchema | undefined {
  const prefix = "#/$defs/";
  if (!reference.startsWith(prefix) || typeof root === "boolean") return undefined;
  return root.$defs?.[reference.slice(prefix.length)];
}

function matchesSchema(value: unknown, schema: JsonSchema, root: JsonSchema): boolean {
  if (schema === true) return true;
  if (schema === false) return false;
  if (schema.$ref) {
    const reference = resolveReference(schema.$ref, root);
    return reference !== undefined && matchesSchema(value, reference, root);
  }
  if (schema.const !== undefined && !Object.is(value, schema.const)) return false;
  if (schema.enum && !schema.enum.some((candidate) => Object.is(value, candidate))) return false;
  if (schema.allOf && !schema.allOf.every((item) => matchesSchema(value, item, root))) return false;
  if (schema.anyOf && !schema.anyOf.some((item) => matchesSchema(value, item, root))) return false;
  if (schema.oneOf && schema.oneOf.filter((item) => matchesSchema(value, item, root)).length !== 1) return false;

  const types = schema.type === undefined ? [] : Array.isArray(schema.type) ? schema.type : [schema.type];
  if (types.length && !types.some((type) => matchesType(value, type))) return false;

  if (typeof value === "string") {
    if (schema.minLength !== undefined && value.length < schema.minLength) return false;
    if (schema.maxLength !== undefined && value.length > schema.maxLength) return false;
  }
  if (typeof value === "number") {
    if (!Number.isFinite(value)) return false;
    if (schema.minimum !== undefined && value < schema.minimum) return false;
    if (schema.maximum !== undefined && value > schema.maximum) return false;
    if (schema.exclusiveMinimum !== undefined && value <= schema.exclusiveMinimum) return false;
    if (schema.exclusiveMaximum !== undefined && value >= schema.exclusiveMaximum) return false;
  }
  if (Array.isArray(value)) {
    if (schema.minItems !== undefined && value.length < schema.minItems) return false;
    if (schema.maxItems !== undefined && value.length > schema.maxItems) return false;
    if (schema.prefixItems && !schema.prefixItems.every((item, index) => {
      const tupleValue = value[index];
      return tupleValue !== undefined && matchesSchema(tupleValue, item, root);
    })) return false;
    const itemSchema = schema.items;
    if (itemSchema && !value.every((item) => matchesSchema(item, itemSchema, root))) return false;
  }
  if (isRecord(value)) {
    if (schema.required?.some((key) => !Object.hasOwn(value, key))) return false;
    for (const [key, propertySchema] of Object.entries(schema.properties ?? {})) {
      if (Object.hasOwn(value, key) && !matchesSchema(value[key], propertySchema, root)) return false;
    }
    if (schema.additionalProperties === false) {
      const properties = schema.properties ?? {};
      if (Object.keys(value).some((key) => !Object.hasOwn(properties, key))) return false;
    } else {
      const additionalProperties = schema.additionalProperties;
      if (!additionalProperties || typeof additionalProperties !== "object") return true;
      const properties = schema.properties ?? {};
      if (Object.entries(value).some(([key, item]) => !Object.hasOwn(properties, key) && !matchesSchema(item, additionalProperties, root))) return false;
    }
  }
  return true;
}

function matchesType(value: unknown, type: string): boolean {
  switch (type) {
    case "array": return Array.isArray(value);
    case "object": return isRecord(value);
    case "string": return typeof value === "string";
    case "number": return typeof value === "number" && Number.isFinite(value);
    case "integer": return typeof value === "number" && Number.isInteger(value);
    case "boolean": return typeof value === "boolean";
    case "null": return value === null;
    default: return true;
  }
}

function isVersionedDesktopReport(value: unknown): value is Record<string, unknown> {
  return isRecord(value) && value.response_version === 1;
}

export function isCheckResult(value: unknown): value is CheckResult {
  return isVersionedDesktopReport(value) && matchesSchema(value, desktopContractSchemas["CheckResult"], desktopContractSchemas["CheckResult"]);
}

export function isEngineHandshakeReport(value: unknown): value is EngineHandshakeReport {
  return isVersionedDesktopReport(value) && matchesSchema(value, desktopContractSchemas["EngineHandshakeReport"], desktopContractSchemas["EngineHandshakeReport"]);
}

export function isHitTestReport(value: unknown): value is HitTestReport {
  return isVersionedDesktopReport(value) && matchesSchema(value, desktopContractSchemas["HitTestReport"], desktopContractSchemas["HitTestReport"]);
}

export function isLayerTreeReport(value: unknown): value is LayerTreeReport {
  return isVersionedDesktopReport(value) && matchesSchema(value, desktopContractSchemas["LayerTreeReport"], desktopContractSchemas["LayerTreeReport"]);
}

export function isPreviewProjectReport(value: unknown): value is PreviewProjectReport {
  return isVersionedDesktopReport(value) && matchesSchema(value, desktopContractSchemas["PreviewProjectReport"], desktopContractSchemas["PreviewProjectReport"]);
}

export function isProjectPolicyReport(value: unknown): value is ProjectPolicyReport {
  return isVersionedDesktopReport(value) && matchesSchema(value, desktopContractSchemas["ProjectPolicyReport"], desktopContractSchemas["ProjectPolicyReport"]);
}

export function isProjectSnapshotReport(value: unknown): value is ProjectSnapshotReport {
  return isVersionedDesktopReport(value) && matchesSchema(value, desktopContractSchemas["ProjectSnapshotReport"], desktopContractSchemas["ProjectSnapshotReport"]);
}

export function isProjectUIMetadataReport(value: unknown): value is ProjectUIMetadataReport {
  return isVersionedDesktopReport(value) && matchesSchema(value, desktopContractSchemas["ProjectUIMetadataReport"], desktopContractSchemas["ProjectUIMetadataReport"]);
}

export function isProposalActionReport(value: unknown): value is ProposalActionReport {
  return isVersionedDesktopReport(value) && matchesSchema(value, desktopContractSchemas["ProposalActionReport"], desktopContractSchemas["ProposalActionReport"]);
}

export function isProposalListReport(value: unknown): value is ProposalListReport {
  return isVersionedDesktopReport(value) && matchesSchema(value, desktopContractSchemas["ProposalListReport"], desktopContractSchemas["ProposalListReport"]);
}

export const desktopContractGuards: Readonly<Record<DesktopContractName, DesktopContractGuard>> = {
  "CheckResult": isCheckResult,
  "EngineHandshakeReport": isEngineHandshakeReport,
  "HitTestReport": isHitTestReport,
  "LayerTreeReport": isLayerTreeReport,
  "PreviewProjectReport": isPreviewProjectReport,
  "ProjectPolicyReport": isProjectPolicyReport,
  "ProjectSnapshotReport": isProjectSnapshotReport,
  "ProjectUIMetadataReport": isProjectUIMetadataReport,
  "ProposalActionReport": isProposalActionReport,
  "ProposalListReport": isProposalListReport,
};
