"""Frozen-binary entry point: hands straight to the normal CLI ``main``.

PyInstaller needs a real script to analyse, and the console-script shim generated by the wheel
is not one. This module adds nothing to the CLI — the frozen binary and ``arcavex`` on PATH run
the identical code path, so behaviour cannot drift between the packaged and installed engine.
"""

from __future__ import annotations

import multiprocessing

from arcavex.clients.cli import main

if __name__ == "__main__":
    # Windows spawns a fresh interpreter for child processes; without this a frozen build would
    # re-run the CLI in every child instead of the worker function.
    multiprocessing.freeze_support()
    main()
